export enum EnvVariables {
  /* DATABASE VARIABLES */
  DATABASE_TYPE = 'DATABASE_TYPE',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_USER = 'DATABASE_USER',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_URI = 'DATABASE_URI',

  /* APP VARIABLES */
  APPLICATION_PORT = 'APPLICATION_PORT',
  APPLICATION_CONTEXT_PATH = 'APPLICATION_CONTEXT_PATH',
}
